function ConnectResult = Connect(obj,Address)
%Connect(obj,Address)
%
%     Input:
%       Address = (string)
%   
%     Output:
%       ConnectResult = (string)

% Build up the argument lists.
values = { ...
   Address, ...
   };
names = { ...
   'Address', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'Connect', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/Connect', ...
    soapMessage);
ConnectResult = parseSoapResponse(response);
