function GetBlockSizeResult = GetBlockSize(obj)
%GetBlockSize(obj)
%
%     Input:
%   
%     Output:
%       GetBlockSizeResult = (unsignedInt)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'GetBlockSize', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/GetBlockSize', ...
    soapMessage);
GetBlockSizeResult = parseSoapResponse(response);
