function GetLOFreqResult = GetLOFreq(obj)
%GetLOFreq(obj)
%
%     Input:
%   
%     Output:
%       GetLOFreqResult = (double)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'GetLOFreq', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/GetLOFreq', ...
    soapMessage);
GetLOFreqResult = parseSoapResponse(response);
