function GetMeasurementForChannelResult = GetMeasurementForChannel(obj,channel,name)
%GetMeasurementForChannel(obj,channel,name)
%
%     Input:
%       channel = (string)
%       name = (string)
%   
%     Output:
%       GetMeasurementForChannelResult = (double)

% Build up the argument lists.
values = { ...
   channel, ...
   name, ...
   };
names = { ...
   'channel', ...
   'name', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'GetMeasurementForChannel', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/GetMeasurementForChannel', ...
    soapMessage);
GetMeasurementForChannelResult = parseSoapResponse(response);
