function GetNumberOfAcquisitionsResult = GetNumberOfAcquisitions(obj)
%GetNumberOfAcquisitions(obj)
%
%     Input:
%   
%     Output:
%       GetNumberOfAcquisitionsResult = (unsignedInt)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'GetNumberOfAcquisitions', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/GetNumberOfAcquisitions', ...
    soapMessage);
GetNumberOfAcquisitionsResult = parseSoapResponse(response);
