function GetRecordLengthResult = GetRecordLength(obj)
%GetRecordLength(obj)
%
%     Input:
%   
%     Output:
%       GetRecordLengthResult = (unsignedInt)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'GetRecordLength', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/GetRecordLength', ...
    soapMessage);
GetRecordLengthResult = parseSoapResponse(response);
