function GetScopeIDNResult = GetScopeIDN(obj)
%GetScopeIDN(obj)
%
%     Input:
%   
%     Output:
%       GetScopeIDNResult = (string)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'GetScopeIDN', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/GetScopeIDN', ...
    soapMessage);
GetScopeIDNResult = parseSoapResponse(response);
