function IsAcquiringResult = IsAcquiring(obj)
%IsAcquiring(obj)
%
%     Input:
%   
%     Output:
%       IsAcquiringResult = (boolean)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'IsAcquiring', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/IsAcquiring', ...
    soapMessage);
IsAcquiringResult = parseSoapResponse(response);
