function IsCancellingResult = IsCancelling(obj)
%IsCancelling(obj)
%
%     Input:
%   
%     Output:
%       IsCancellingResult = (boolean)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'IsCancelling', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/IsCancelling', ...
    soapMessage);
IsCancellingResult = parseSoapResponse(response);
