function IsRunningResult = IsRunning(obj)
%IsRunning(obj)
%
%     Input:
%   
%     Output:
%       IsRunningResult = (boolean)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'IsRunning', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/IsRunning', ...
    soapMessage);
IsRunningResult = parseSoapResponse(response);
