function IsScopeConnectedResult = IsScopeConnected(obj)
%IsScopeConnected(obj)
%
%     Input:
%   
%     Output:
%       IsScopeConnectedResult = (boolean)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'IsScopeConnected', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/IsScopeConnected', ...
    soapMessage);
IsScopeConnectedResult = parseSoapResponse(response);
