function LoadState(obj,stateName,loadSoftware,loadHardware)
%LoadState(obj,stateName,loadSoftware,loadHardware)
%
%     Input:
%       stateName = (string)
%       loadSoftware = (boolean)
%       loadHardware = (boolean)
%   
%     Output:

% Build up the argument lists.
values = { ...
   stateName, ...
   loadSoftware, ...
   loadHardware, ...
   };
names = { ...
   'stateName', ...
   'loadSoftware', ...
   'loadHardware', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}boolean', ...
   '{http://www.w3.org/2001/XMLSchema}boolean', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'LoadState', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/LoadState', ...
    soapMessage);
parseSoapResponse(response);
