function SaveState(obj,stateName,saveSoftware,saveHardware)
%SaveState(obj,stateName,saveSoftware,saveHardware)
%
%     Input:
%       stateName = (string)
%       saveSoftware = (boolean)
%       saveHardware = (boolean)
%   
%     Output:

% Build up the argument lists.
values = { ...
   stateName, ...
   saveSoftware, ...
   saveHardware, ...
   };
names = { ...
   'stateName', ...
   'saveSoftware', ...
   'saveHardware', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}boolean', ...
   '{http://www.w3.org/2001/XMLSchema}boolean', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'SaveState', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/SaveState', ...
    soapMessage);
parseSoapResponse(response);
