function SetLOFreq(obj,loFreq)
%SetLOFreq(obj,loFreq)
%
%     Input:
%       loFreq = (double)
%   
%     Output:

% Build up the argument lists.
values = { ...
   loFreq, ...
   };
names = { ...
   'loFreq', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}double', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'SetLOFreq', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/SetLOFreq', ...
    soapMessage);
parseSoapResponse(response);
