function SetMulticarrierChannelList(obj,name)
%SetMulticarrierChannelList(obj,name)
%
%     Input:
%       name = (string)
%   
%     Output:

% Build up the argument lists.
values = { ...
   name, ...
   };
names = { ...
   'name', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'SetMulticarrierChannelList', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/SetMulticarrierChannelList', ...
    soapMessage);
parseSoapResponse(response);
