function SetOfflineFiles(obj,fileNames)
%SetOfflineFiles(obj,fileNames)
%
%     Input:
%       fileNames = (ArrayOfstring)
%   
%     Output:

% Build up the argument lists.
values = { ...
   fileNames, ...
   };
names = { ...
   'fileNames', ...
   };
types = { ...
   '{http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfstring', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://tempuri.org/', ...
    'SetOfflineFiles', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://tempuri.org/IWCFServiceOM4006Basic/SetOfflineFiles', ...
    soapMessage);
parseSoapResponse(response);
